name: Deploy Synthwave Outfit

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Mod to Steam Workshop
        uses: thegamerbay/haydee-workshop-upload@v1
        with:
          id: '3670764079'
          folder: 'Outfits'
          pack_name: 'SynthwaveOutfit.pack'
          priority: '2'
          changelog: 'Release ${{ github.ref_name }}'
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
